apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: iiif-api-admin-secret
  namespace: journal--prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: iiif-api-admin-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: journal-team/iiif/api-admin
