apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: journal
resources:
- secret-securityconfig.yaml
- secret-admin-creds.yaml
- cluster.yaml
- serviceaccount.yaml
- servicemonitor.yaml
- snapshotpolicy.yaml
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: search
    app.kubernetes.io/instance: search-${env}
    app.kubernetes.io/component: opensearch
    app.kubernetes.io/name: opensearch
