---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jats-to-pdf
  namespace: journal
spec:
  template:
    spec:
      securityContext:
        securityContext:
          seccompProfile:
            type: RuntimeDefault
      containers:
      - name: jats-to-pdf
        image: ghcr.io/elifesciences/jats-to-pdf:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: 2000Mi
          requests:
            cpu: 1
            memory: 1900Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          periodSeconds: 2
          failureThreshold: 5
          timeoutSeconds: 2
