---
kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
  name: jats-to-pdf
spec:
  hosts:
  - "${hostname}"
  - "test-${hostname}"
  pathPrefixes:
  - /
  scaleTargetRef:
    name: jats-to-pdf
    kind: Deployment
    apiVersion: apps/v1
    service: jats-to-pdf-api
    port: 3000
  replicas:
    min: 1
    max: 10
  scaledownPeriod: 300
  scalingMetric:
    concurrency:
      targetValue: 2
