---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jats-to-pdf
  namespace: journal
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 4m
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  rules:
  - host: ${hostname}
    http:
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: jats-to-pdf-api
              port:
                number: 3000
  tls:
  - hosts:
    - ${hostname}
    secretName: ${hostname}-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jats-to-pdf-scaler-test
  namespace: journal
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 4m
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  rules:
  - host: test-${hostname}
    http:
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: jats-to-pdf-api-scaler
              port:
                number: ${keda_port:=8080}
  tls:
  - hosts:
    - test-${hostname}
    secretName: test-${hostname}-tls
