---
apiVersion: v1
kind: Service
metadata:
  name: jats-to-pdf-api-scaler
  namespace: journal
spec:
  type: ExternalName
  externalName: ${keda_proxy:-'keda-add-ons-http-interceptor-proxy.keda.svc.cluster.local'}
