apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    traefik.ingress.kubernetes.io/router.middlewares: journal-prod-2016-redirect@kubernetescrd
  name: 2016-redirect
  namespace: journal--prod
spec:
  ingressClassName: traefik
  rules:
    - host: 2016.elifesciences.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dummy-http-svc
                port:
                  number: 80
  tls:
    - hosts:
        - 2016.elifesciences.org
      secretName: 2016.elifesciences.org-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: journal-prod-2016-redirect@kubernetescrd
    cert-manager.io/cluster-issuer: "letsencrypt"
  name: 2016-redirect-traefik
  namespace: journal--prod
spec:
  ingressClassName: traefik
  rules:
    - host: 2016.elifesciences.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dummy-http-svc
                port:
                  number: 80
  tls:
    - hosts:
        - 2016.elifesciences.org
      secretName: 2016.elifesciences.org-tls
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: 2016-redirect
  namespace: journal--prod
spec:
  redirectRegex:
    regex: ".*"
    replacement: https://elifesciences.org/inside-elife/d457b4cd
    permanent: true
