apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jats-to-pdf
  namespace: journal--prod
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: journal-team-deployment
    namespace: flux-system
  path: ./kustomizations/jats-to-pdf
  prune: true
  targetNamespace: journal--prod
  images:
  - name: ghcr.io/elifesciences/jats-to-pdf # {"$imagepolicy": "journal--prod:jats-to-pdf-stable:name"}
    newTag: main-c35aac88-20260206.0942 # {"$imagepolicy": "journal--prod:jats-to-pdf-stable:tag"}
  postBuild:
    substitute:
      env: prod
      hostname: jats-to-pdf.prod.elifesciences.org
