apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: journal-downloads
  namespace: journal--prod
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: journal-team-deployment
    namespace: flux-system
  path: ./kustomizations/journal/downloads
  prune: true
  targetNamespace: journal--prod
  dependsOn:
  - name: journal-downloads-role
  images:
  - name: ghcr.io/elifesciences/journal-downloads # {"$imagepolicy": "journal--prod:journal-downloads:name"}
    newTag: 20251208135835.0.0-g0ac7647-20030612834-1 # {"$imagepolicy": "journal--prod:journal-downloads:tag"}
  postBuild:
    substituteFrom:
    # role_arn are retrieved from the configmap
    - kind: ConfigMap
      name: journal-downloads-role
    substitute:
      # deployment vars
      env: prod
      replicas: "5"
      hostname: journal.prod.elifesciences.org
      allowed_hosts: elifesciences.org, journal.prod.elifesciences.org
      cert_manager_issuer: "letsencrypt"
      secret_name: journal-downloads-secret
      aws_endpoint: s3.us-east-1.amazonaws.com
      aws_region: us-east-1
      proxy_config: cdn.elifesciences.org:s3://elife-cdn,cdn.elifesciences.org/articles:s3://prod-elife-published,cdn.elifesciences.org/preprints:s3://prod-elife-published,iiif.elifesciences.org:http://cantaloupe.journal--prod:8080
